manifest = "e68c93845bcd3d169b0b980a335e2d7689a89f346b00c445a130bef8d470caaa"

[[dependency]]
package = "github.com/buckaroo-pm/boost-config"
target = "//:config"

[[dependency]]
package = "github.com/buckaroo-pm/boost-detail"
target = "//:detail"

[[dependency]]
package = "github.com/buckaroo-pm/boost-function_types"
target = "//:function_types"

[[dependency]]
package = "github.com/buckaroo-pm/boost-mpl"
target = "//:mpl"

[[dependency]]
package = "github.com/buckaroo-pm/boost-preprocessor"
target = "//:preprocessor"

[[dependency]]
package = "github.com/buckaroo-pm/boost-type_traits"
target = "//:type_traits"

[lock."github.com/buckaroo-pm/boost-config"]
versions = [ "1.67.0" ]
revision = "5782f108397199eccd4404780d37513b42798a43"

[lock."github.com/buckaroo-pm/boost-detail"]
versions = [ "1.67.0" ]
revision = "feb7fef2d9afa1f1e2f33d4a6a2d9d63aadd1d24"

[lock."github.com/buckaroo-pm/boost-function_types"]
versions = [ "1.67.0" ]
revision = "bb6ed755fa37d53a3e9d1bbda3fbdfada752d396"

[lock."github.com/buckaroo-pm/boost-mpl"]
versions = [ "1.67.0" ]
revision = "ba6d295fef8ce71a4cf0a286e4e0ade60e3d6b74"

[lock."github.com/buckaroo-pm/boost-preprocessor"]
versions = [ "1.67.0" ]
revision = "aa51a0a1e2936c78fa448bdada5a0ca6754f0b54"

[lock."github.com/buckaroo-pm/boost-type_traits"]
versions = [ "1.67.0" ]
revision = "7554865aad1e357c2ce1300060e87f1f44f9d3b0"
